feat(smoke-test): adding smoke test before pushing

diff --git a/.github/workflows/newci.yaml b/.github/workflows/newci.yaml
--- a/.github/workflows/newci.yaml
+++ b/.github/workflows/newci.yaml
@@ -82,7 +82,21 @@ jobs:
           grype ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} 
 
 
-        
+      - name: Smoke test
+        run: |
+          docker run -d -p 5000:3000 --name smoke_test_container \
+          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
+          
+          sleep 5
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000)
+          if [ "$RESPONSE" -ne 200 ]; then
+                echo "Smoke test failed: HTTP $RESPONSE"
+                exit 1
+          else
+             echo "Smoke test passed!"
+          fi
+
+           
           
       - name: Push Docker image
         uses: docker/build-push-action@v5
